name:                effev
version:             0.1.0.0
github:              "xnning/effev"
license:             MIT
author:              "Daan Leijen, Ningning Xie"
maintainer:          "xnning@hku.hk;daan@microsoft.com"
copyright:           "(c) 2020, Microsoft Research, Daan Leijen, Ningning Xie"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  See the "Control.Ev.Eff" module for further information
  (or the README on GitHub at <https://github.com/xnning/effev#readme>).


dependencies:
- base >= 4.7 && < 5
- primitive
- ghc-prim
- criterion
- random
- containers
- mtl
- extensible-effects

library:
  source-dirs: src
  
executables:
  TestAOP:
    main:                TestAOP.hs
    source-dirs:         app
    ghc-options:
    - -main-is TestAOP
    - -O3
    - -Wno-simplifiable-class-constraints
    dependencies:
    - effev

  TestQueens:
    main:                TestQueens.hs
    source-dirs:         app
    ghc-options:
    - -main-is TestQueens
    - -O3
    - -Wno-simplifiable-class-constraints
    dependencies:
    - effev

  TestState:
    main:                TestState.hs
    source-dirs:         app
    ghc-options:
    - -main-is TestState
    - -O3
    - -Wno-simplifiable-class-constraints
    dependencies:
    - effev

  ProfState:
    main:                TestState.hs
    source-dirs:         app
    ghc-options:
    - -Wno-simplifiable-class-constraints
    - -main-is TestState
    - -O3
    - -fforce-recomp
    - -ddump-simpl -dsuppress-idinfo -dsuppress-coercions -dsuppress-type-applications -dsuppress-uniques -dsuppress-module-prefixes -ddump-to-file
    dependencies:
    - effev

  TestLayer:
    main:                TestLayer.hs
    source-dirs:         app
    ghc-options:
    - -main-is TestLayer
    - -O3
    - -Wno-simplifiable-class-constraints
    dependencies:
    - effev

  TestPyth:
    main:                TestPyth.hs
    source-dirs:         app
    ghc-options:
    - -main-is TestPyth
    - -O3
    - -Wno-simplifiable-class-constraints
    dependencies:
    - effev
